Homeworks/12.1
ZazzizzuzA/mpylypenko-hillel-javabase pull request #12
Opened 2024-12-17 17:09 UTC by ZazzizzuzA

2024-12-18 00:33 UTC, JIeIIIa requested changes

2024-12-18 00:33 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw121/DemoClass.java
> +        Scanner scanner = new Scanner(System.in);
Ми вже розглянули статичні змінні. Немає сенсу на кожен виклик методу створювати окремий обʼєкт `Scanner`. Це не дуже елегантно, але раз вже використовуєш статичні методи, то зроби статичну змінну і використовуй її

2024-12-18 00:33 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw121/DemoClass.java
> +    private static String askClientString(String text) {
Я б методи назвав `readString`/`readInt`. Префікс `askClient` можна б опустити і читаємість коду від цього не погіршиться. Тому що насправді чи на стільки важливо хто саме тут буде вводити дані?;)

2024-12-18 00:33 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw121/Worker.java
> +    public void printInfo() {
Ми знаємо вже про методи класу `Object`. Тому доцільніше було перевизначити метод `toString()` Таким чином з класу зніметься одна відповідальність: виводити інформацію про себе у консоль.
Якщо такий же текст потрібно буде завтра ще відправляти поштою, то зараз тобі текст потрібно буде продублювати в іншому методі - це погано.

2024-12-18 17:28 UTC, ZazzizzuzA commented on src/com/gmail/mpylypenko/homeworks/hw121/Worker.java
> +    public void printInfo() {
Не зрозумів.

2024-12-18 18:42 UTC, JIeIIIa requested changes

2024-12-18 18:42 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw121/Worker.java
> +    public void printInfo() {
Подивись про[ принцип єдиної відповідальності](https://uk.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF_%D1%94%D0%B4%D0%B8%D0%BD%D0%BE%D1%97_%D0%B2%D1%96%D0%B4%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D1%96)
Якщо все одно буде не зрозуміло, то напиши в Телеграмі - обговоримо

2024-12-19 00:22 UTC, JIeIIIa approved these changes

2024-12-19 00:22 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw121/Worker.java
> +        return "Hi! My name is " + this.getName() + ".\n" +
Не звернув уваги раніше, але казав про це на лекції: якщо гетер тільки повертає значення поля, то замість виклику методу в середині класу простіше (краще) звернутись безпосередньо до поля. Ми захищаємо дані ззовні, але в середині класу можемо працювати з полями напряму. Врахуй це у майбутньому.

2024-12-19 00:22 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw121/DemoClass.java
> +        System.out.println(worker.toString());
Метод toString() буде неявно викликаний. Достатньо
```
System.out.println(worker);
```
До речі, IDEA мала б сірим даний метод підсвітити. Зазвичай те, що підсвічено сірим, можна видаляти.

2024-12-19 18:30 UTC, merged