create demoClass for geometry figures
ZazzizzuzA/mpylypenko-hillel-javabase pull request #13
Opened 2024-12-18 17:30 UTC by ZazzizzuzA

2024-12-18 18:35 UTC, JIeIIIa requested changes

2024-12-18 18:35 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw131/GeometryFigure.java
> +    double plane();
Не впевнений, що plane використовується в значенні площа. Це скоріше площина або літак. Я б тут очікував побачити **area**, наприклад. Але, можливо, і plane має право на життя)

2024-12-18 18:35 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw131/Square.java
> +    private double sideValue;
value зайве. можна просто `side`

2024-12-18 18:35 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw131/Triangle.java
> +            Random random = new Random();
Так робити не раціонально. Ти додаєш роботи Garbage Collector'у. Краще створити один обʼєкт `Random` перед циклом і потім його використовуати. Зараз ти створиш 3 обʼєкта

2024-12-18 18:35 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw131/Triangle.java
> +        return Math.floor(((this.height() * this.sides[0]) / 2) * 100) / 100;
Ти знов перемудрував( Давай у цю формулу підставимо значення для розрахунку висоти (заокруглення я опущу)
```
(this.height() * this.sides[0]) / 2 ==
(this.sides[2] * this.sides[1] / this.sides[0] * this.sides[0]) / 2 ==
(this.sides[2] * this.sides[1]) / 2
```
Окрім розрахункув і "зайвого" методу проблема в тому, що ти у користувача запитуєш три сторони (тобто не накладаєш обмеження на трикутник), а при обчисленні вважаєш трикутник прямокутним. Або ж запитуй і зберігай дві сторони, або ж коректно розраховуй (напр, по [формулі Герона](https://www.mathros.net.ua/teorema-gerona.html) через напівпериметр)

2024-12-18 18:35 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw131/PolymorphPractice.java
> +    private static double sumOfAllPlanes(GeometryFigure[] figures) {
OfAll з назви я б викинув. Якогось навантаження ця частка не несе. Взагалі в назва не прийнято використовувати of/a/the

2024-12-18 20:16 UTC, ZazzizzuzA commented on src/com/gmail/mpylypenko/homeworks/hw131/GeometryFigure.java
> +    double plane();
Теж сумнівався)

2024-12-19 00:35 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw131/PolymorphPractice.java
> +    private static double sumOfAllPlanes(GeometryFigure[] figures) {
Якщо вже plane перейменував в area, то варто було і в назві методу це змінити

2024-12-19 00:35 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw131/Triangle.java
> +        return Math.floor(((this.height() * this.sides[0]) / 2) * 100) / 100;
Ти все ще запитуєш 3 сторони, а працюєш з двома (як з прямокутним трикутником). Зміни або формулу для розрахунку, або ж зберігай два катети. Трикутник зі сторонами `new double[]{9, 3, 7}` має площу 8.79, а твоя програма каже що 10.5

2024-12-22 20:18 UTC, merged