Homeworks/15.1
ZazzizzuzA/mpylypenko-hillel-javabase pull request #15
Opened 2024-12-22 22:22 UTC by ZazzizzuzA

2024-12-23 11:52 UTC, JIeIIIa requested changes

2024-12-23 11:52 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw151/Day.java
> +    UNKNOWN("UNKNOWN DAY");
хіба є невідомий день тижня у нас? це зайве значення

2024-12-23 11:52 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw151/DemoAdviser.java
> +        } while(counter > 0);
Вийшов цикл заради циклу( За якої умови цикл виконається двічі? Або хоча б коли виконання дійди до цього рядка?

2024-12-23 11:52 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw151/DemoAdviser.java
> +        selection = scanner.nextInt();
на мою думку краще оголошувати змінну максимально близько до першого використання. тоді мало б бути
```
int selection = scanner.nextInt();
```

2024-12-23 11:52 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw151/DemoAdviser.java
> +        System.out.println("Select your day:");
Не певен, що тобі потрібен масив в параметрах та метод `getListDays()`. У всіх `enum` є метод `values()`, який поверне перелік всіх значень. Можна б було зробити
```
Day[] days = Day.values();
for (int i = 1; i <= days.length; i++) {
    System.out.println(i + " - " + days[i - 1].name());
}
```

2024-12-23 16:37 UTC, ZazzizzuzA commented on src/com/gmail/mpylypenko/homeworks/hw151/DemoAdviser.java
> +        selection = scanner.nextInt();
Та вона тут взагалі не потрібна. Можна inline:
`return scanner.nextInt();`

2024-12-24 10:25 UTC, JIeIIIa approved these changes

2024-12-26 16:41 UTC, merged