homework 10.1: all methods are set
ZazzizzuzA/mpylypenko-hillel-javabase pull request #8
Opened 2024-11-28 17:38 UTC by ZazzizzuzA

2024-11-29 11:57 UTC, JIeIIIa requested changes

2024-11-29 11:57 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw101/CustomMethods.java
> +    private static void printTextWithRepeats(String text, int repeats) {
Не помилка, але... можна було назвати просто print(). Читатись код, з урахуванням параметрів, буде так: "print... text... repeats"

2024-11-29 11:57 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw101/CustomMethods.java
> +    private static int powNumber(int number, int powerNumber) {
Не всі випадки враховано. Обмеження ж тільки що параметри - цілі числа. Якщо я захочу обчислити 10^(-1), то отримаю відповідь 10 чомусь. А мав би 0.1

2024-11-29 11:57 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw101/CustomMethods.java
> +    private static int integerInSecondPow(int integer) {
integerInSecondPow - square 
integer - number or value
так було б краще, імхо

2024-11-29 11:57 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw101/CustomMethods.java
> +        char[] arrayChars = text.toCharArray();
А навіщо окрема змінна? Можна було б зробити
```
for (int i = text.length() - 1; i >= 0; i--) {
    reverseText += text.charAt(i);
}
```

2024-12-01 19:07 UTC, JIeIIIa requested changes, later dismissed

2024-12-01 19:07 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw101/CustomMethods.java
> +        for (int i = isNegativePower ? powerNumber * -1 : powerNumber; i > 1; i--) {
Це спроба винайти модуль числа. Можна б було використати `Math.abs()`
Замість `powerNumber * -1` можна б було написати просто `-powerNumber`

2024-12-01 19:07 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw101/CustomMethods.java
> +        return isNegativePower ? (double) 1 / poweredNumber : poweredNumber;
Замість приведення типу можна було одразу вказати потрібний тип ;)
`(double) 1` -> `1.0ʼ

2024-12-01 19:11 UTC, ZazzizzuzA commented on src/com/gmail/mpylypenko/homeworks/hw101/CustomMethods.java
> +        return isNegativePower ? (double) 1 / poweredNumber : poweredNumber;
аааа... так ось чому ідеа мене так виправляла)

2024-12-01 19:26 UTC, JIeIIIa approved these changes

2024-12-01 21:00 UTC, merged