homework 11.1: Person class is ready
ZazzizzuzA/mpylypenko-hillel-javabase pull request #9
Opened 2024-12-01 22:07 UTC by ZazzizzuzA

Функціонал з дефолтними персонами для експерименту і цікавинки)

2024-12-07 14:23 UTC, JIeIIIa requested changes

2024-12-07 14:23 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw111/Person.java
> +        int index = random.nextInt(1, names.length);
В поточній імплементації не вийде отримати Steve, 13, Stalker. Індексація масивів починається з нуля, а нижня межа 1. Варто б було використати
```
random.nextInt(names.length);
```

2024-12-07 14:23 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw111/Person.java
> +        setName(name);
Про сетери ми ще будемо розмовляти, тому зараз це не вважається помилкою. Але, якщо сетер тільки змінює значення, то немає сенсу викликати його (окремий метод) в середині класу. Краще б було зробити
```
   this.name = name;
   this.age = age;
   this.profession = profession;
```

2024-12-07 14:23 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw111/CreatePerson.java
> +    private static void print(Person person) {
це мав би бути метод в класі `Person`. Тобто кожен обʼєкт "розповідає" хто він такий

2024-12-07 14:23 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw111/CreatePerson.java
> +        Person person1 = createPerson(useDefaultValues);
Назви змінних, які відрізняються одним символом все ще погана ідея. Якщо не хочеш придумувати назви змінним, то можна б було використати масив
```
Person[] persons = {
    createPerson(useDefaultValues),
    createPerson(useDefaultValues),
    createPerson(useDefaultValues)
};
```

2024-12-07 14:23 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw111/CreatePerson.java
> +    private static Person createPerson(boolean useDefaultValues) {
параметри-флаги - погана практика. Краще мати два методи з однаковим іменем, але різною сигнатурою або ж два методи з різними іменами. Буває, коли передають не один, а 3, 5 або більше флагів. Проконтролювати, що порядок true/false значень у виклику такого метода вірний доволі важко

2024-12-07 14:23 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw111/Person.java
> +        int[] ages = {13,65,76,45,3,34,54,72,98,12,54};
форматування! не вистачає пробілів після ком. Ctrl+Alt+L врятувало б ситуацію

2024-12-08 20:14 UTC, ZazzizzuzA commented on src/com/gmail/mpylypenko/homeworks/hw111/Person.java
> +        setName(name);
Ок. 
Але це більше для можливості редагування ззовні. Зовнішнє API.

2024-12-08 20:53 UTC, ZazzizzuzA commented on src/com/gmail/mpylypenko/homeworks/hw111/CreatePerson.java
> +    private static Person createPerson(boolean useDefaultValues) {
Так, буду вчитись не використовувати флаги.

2024-12-09 08:08 UTC, JIeIIIa approved these changes

2024-12-09 08:08 UTC, JIeIIIa commented on src/com/gmail/mpylypenko/homeworks/hw111/CreatePerson.java
> +        persons[0].printInfo();
Не помилка, але можна було б використати for each;)
```
for (Person person : persons) {
    person.printInfo();
}

2024-12-10 19:40 UTC, merged